#' Run LDA across a range of questions each with a range of topic numbers
#'
#' Function will run a series of Latent Dirichlet Allocation models across
#' questions for a range of topic numbers using the passed seed.
#'
#' @param data data frame containing response text and ids for all questions.
#' @param col_resp_id character string of column containing response id.
#' @param question_topic_ranges named list with names corresponding to
#'   questions to analyse and values integer vectors giving range of topic
#'   numbers to try.
#' @param seed integer used to seed random number generator for Gibbs sampling.
#' @param clean_text_fn function used to clean question text.
#' @param glossary_words character vector of multi-word terms to be replaced
#'   with single word equivalents (set to NULL to ignore).
#' @param stop_words character vector of common words to be removed from
#'   un-nested values (set to NULL to ignore).
#' @param stem_word_exceptions character vector of terms not to stem (set to
#'   NULL to ignore). Note these strings must match exactly.
#'
#' @return returns named list with names corresponding to questions and values
#'   being further named lists with these names being the topic number and the
#'   values the output of the LDA model.
#' @export
#'
#' @importFrom rlang :=
#'
fit_lda <- function(
  data,
  col_resp_id,
  question_topic_ranges,
  seed,
  clean_text_fn,
  glossary_words,
  stop_words,
  stem_word_exceptions
) {
  assert_data_frame(data)
  assert_string(col_resp_id)
  assert_list(question_topic_ranges, types = c("integerish"), names = "named")
  assert_integerish(seed, len = 1)
  assert_function(clean_text_fn)
  assert_character(glossary_words, null.ok = TRUE)
  assert_character(stop_words, null.ok = TRUE)
  assert_character(stem_word_exceptions, null.ok = TRUE)

  fn <- function(col) {
    dtm <- data |>
      dplyr::select(dplyr::all_of(c(col_resp_id, col))) |>
      unnest_words(
        col,
        clean_text_fn = clean_text_fn,
        glossary_words = glossary_words,
        stop_words = stop_words,
        stem_word_exceptions = stem_word_exceptions
      ) |>
      unnest_to_dtm(col_resp_id, col_word = "word")

    topic_number_range <- question_topic_ranges[[col]]
    future::plan("multisession")

    return(
      topic_number_range |>
        rlang::set_names(as.character(topic_number_range)) |>
        purrr::map(
          \(k) run_lda_dtm(dtm, k, seed),
          .progress = "topic run progress"
        )
    )
  }

  questions <- names(question_topic_ranges)
  lda_out <- questions |>
    rlang::set_names(questions) |>
    furrr::future_map(fn, .progress = TRUE)

  return(lda_out)
}


#' Show plots of LDA fit convergence
#'
#' @param lda_fit_list named list of lists of LDA objects generated by the
#'   [fit_lda()] function.
#'
#' @return invisibly returns passed LDA list object
#' @export
#'
view_lda_fit_convergence <- function(lda_fit_list) {
  assert_list(lda_fit_list, types = c("list"), names = "named")

  questions <- names(lda_fit_list)

  plots_c <- questions |>
    purrr::map(\(x) plot_lda_convergence(lda_fit_list[[x]], x))

  plots_c |>
    purrr::map(print)

  return(invisible(lda_fit_list))
}


#' Show plots of LDA fit log-likelihood
#'
#' @param lda_fit_list named list of lists of LDA objects generated by the
#'   [fit_lda()] function.
#'
#' @return invisibly returns passed LDA list object
#' @export
#'
view_lda_fit_loglikelihood <- function(lda_fit_list) {
  assert_list(lda_fit_list, types = c("list"), names = "named")

  questions <- names(lda_fit_list)

  plots_l <- questions |>
    purrr::keep(\(x) length(lda_fit_list[[x]]) > 1) |>
    purrr::map(\(x) plot_lda_k_loglik(lda_fit_list[[x]], x))

  plots_l |>
    purrr::map(print)

  plots_l |>
    patchwork::wrap_plots() |>
    print()

  return(invisible(lda_fit_list))
}


#' Write plots and LDA object to folder
#'
#' Outputs all plots and objects into the specified `folder` using the
#' passed `prefix` when naming files.
#'
#' @param lda_fit_list named list of lists of LDA objects generated by the
#'   [fit_lda()] function.
#' @param folder path to the folder in which to save (will create if not
#'   present).
#' @param prefix prefix to use when naming files (defaults to
#'   `basename(folder)`)
#'
#' @return invisibly returns passed LDA list object
#' @export
#'
write_lda_fit <- function(
  lda_fit_list,
  folder,
  prefix = basename(folder)
) {
  assert_list(lda_fit_list, types = c("list"), names = "named")
  assert_string(folder)
  assert_string(prefix)

  # create output folder if not already present
  dir.create(folder, showWarnings = FALSE, recursive = TRUE)

  questions <- names(lda_fit_list)

  c_plots <- questions |>
    purrr::map(\(x) plot_lda_convergence(lda_fit_list[[x]], x))

  c_plots |>
    seq_along() |>
    purrr::map(
      \(i) {
        write_plot_svg(
          c_plots[[i]],
          file.path(
            folder,
            sprintf("%s_convergence_question_%02d", prefix, i)
          )
        )
      }
    )

  l_plots <- questions |>
    purrr::keep(\(x) length(lda_fit_list[[x]]) > 1) |>
    purrr::map(\(x) plot_lda_k_loglik(lda_fit_list[[x]], x))

  l_plots |>
    patchwork::wrap_plots() |>
    write_plot_svg(
      file.path(
        folder,
        sprintf("%s_loglikelihood_all", prefix)
      )
    )

  l_plots |>
    seq_along() |>
    purrr::map(
      \(i) {
        write_plot_png(
          l_plots[[i]],
          file.path(
            folder,
            sprintf("%s_loglikelihood_question_%02d", prefix, i)
          )
        )
      }
    )

  saveRDS(
    lda_fit_list,
    file.path(
      folder,
      sprintf("%s_fit_object.rds", prefix)
    )
  )

  return(invisible(lda_fit_list))
}
